name: Build with bal test native

on:
    workflow_dispatch:
        inputs:
            build_envs:
                description: Test Environments
                type: choice
                required: true
                options:
                    - Ubuntu
                    - Windows
                    - Ubuntu and Windows
                default: Ubuntu and Windows
            lang_tag:
                description: Branch/Release Tag of the Ballerina Lang
                required: true
                default: master
            lang_version:
                description: Ballerina Lang Version (If given ballerina lang buid will be skipped)
                required: false
                default: ''

jobs:
    ubuntu-build-with-bal-test-native:
        name: Build with bal test native on Ubuntu
        if: ${{ inputs.build_envs != 'Windows' }}
        runs-on: ubuntu-latest

        steps:
            - name: Set up GraalVM
              uses: graalvm/setup-graalvm@v1
              with:
                  version: 'latest'
                  java-version: '11'
                  components: 'native-image'
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Check GraalVM installation
              run: |
                  echo "GRAALVM_HOME: ${{ env.GRAALVM_HOME }}"
                  native-image --version

            - name: Checkout Ballerina Lang Repository
              if: ${{ inputs.lang_version == '' }}
              uses: actions/checkout@v3
              with:
                  repository: 'ballerina-platform/ballerina-lang'
                  ref: ${{ inputs.lang_tag }}

            - name: Set Ballerina Lang version
              run: |
                  if ${{ inputs.lang_version != ''}}; then
                      LANG_VERSION=${{ inputs.lang_version }}
                  else
                      VERSION=$((grep -w 'version' | cut -d= -f2) < gradle.properties | rev | cut --complement -d- -f1 | rev)
                      LANG_VERSION=$VERSION-NATIVE
                  fi
                  echo "BALLERINA_LANG_VERSION=$LANG_VERSION" >> $GITHUB_ENV
                  echo "BALLERINA_LANG_VERSION=$LANG_VERSION"

            - name: Build Ballerina Lang
              if: ${{ inputs.lang_version == '' }}
              run: |
                  perl -pi -e "s/^\s*version=.*/version=${{ env.BALLERINA_LANG_VERSION }}/" gradle.properties
                  ./gradlew build -x check -x test publishToMavenLocal

            - name: Checkout Module Repository
              uses: actions/checkout@v3

            - name: Build with Gradle
              env:
                  packageUser: ${{ github.actor }}
                  packagePAT: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  perl -pi -e "s/^\s*ballerinaLangVersion=.*/ballerinaLangVersion=${{ env.BALLERINA_LANG_VERSION }}/" gradle.properties
                  ./gradlew build -PbalNativeTest

    windows-build-with-bal-test-native:
        name: Build with bal test native on Windows
        if: ${{ inputs.build_envs != 'Ubuntu' }}
        runs-on: windows-latest

        steps:
            - name: Set up GraalVM
              uses: graalvm/setup-graalvm@v1
              with:
                  version: 'latest'
                  java-version: '11'
                  components: 'native-image'
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Check GraalVM installation
              run: |
                  Write-Output GRAALVM_HOME: "${{ env.GRAALVM_HOME }}"
                  Write-Output JAVA_HOME: "${{ env.JAVA_HOME }}"
                  native-image --version

            - name: Checkout Ballerina Lang Repository
              if: ${{ inputs.lang_version == '' }}
              uses: actions/checkout@v3
              with:
                  repository: 'ballerina-platform/ballerina-lang'
                  ref: ${{ inputs.lang_tag }}

            - name: Set Ballerina Lang version
              run: |
                  $properties = convertfrom-stringdata (get-content ./gradle.properties -raw)
                  $VERSION = $properties.'version'.split("-",2)[0]
                  $LANG_VERSION = ("${{ inputs.lang_version }}" -eq "true") ? "${{ inputs.lang_version }}" : $VERSION + "-NATIVE"
                  "BALLERINA_LANG_VERSION=$LANG_VERSION" >> $env:GITHUB_ENV
                  Write-Output "BALLERINA_LANG_VERSION = $LANG_VERSION"

            - name: Build Ballerina Lang
              if: ${{ inputs.lang_version == '' }}
              run: |
                  perl -pi -e "s/^\s*version=.*/version=${{ env.BALLERINA_LANG_VERSION }}/" gradle.properties
                  ./gradlew.bat build -x check -x test publishToMavenLocal

            - name: Checkout Module Repository
              uses: actions/checkout@v3

            - name: Build with Gradle
              env:
                  packageUser: ${{ github.actor }}
                  packagePAT: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  perl -pi -e "s/^\s*ballerinaLangVersion=.*/ballerinaLangVersion=${{ env.BALLERINA_LANG_VERSION }}/" gradle.properties
                  ./gradlew.bat build -x test
                  ./gradlew.bat test -x :http-native:test -PbalNativeTest
